### ISSUE TITLE
Linux downloads not available from website

### ISSUE THREAD

**Issue by jsavage** [bridgecommand/bc#12]
Hi, 
Realy pleased to see this updated.  This is just a quick note to report that the download links for Linux 64 bit (amd64) .deb package and Linux 32 bit (i386) .deb package on the website are not working.

If linux RPMs or similar are not planned, could I please request some simple build instructions.

James

**Comment by bridgecommand** [comment]
Hi. https://www.bridgecommand.co.uk/forum/index.php/topic,2276.msg2810 has some instructions on building for an RPM based system. I'll see if I can build RPMs for future releases. 

The issue with the links on the download page should be fixed (It depended on how you navigated to the Download page, so I did not spot it immediately)
