### ISSUE TITLE
termiate a start | core dump

### ISSUE THREAD

**Issue by ds2k5** [bridgecommand/bc#2]
Hi,

1. git clone https://github.com/bridgecommand/bc
2. cd bc && make

if i run the "bridgecommand-bc" got a error:

$ ./bridgecommand-bc 
terminate called after throwing an instance of 'std::runtime_error'
  what():  locale::facet::_S_create_c_locale name not valid
written Aborted (core dumped)

$ ldd bridgecommand-bc 
	linux-vdso.so.1 (0x00007fff25f91000)
	libIrrlicht.so.1.8 => /usr/lib/libIrrlicht.so.1.8 (0x00007f32473f4000)
	libGL.so.1 => /usr/lib/libGL.so.1 (0x00007f3247182000)
	libXxf86vm.so.1 => /usr/lib/libXxf86vm.so.1 (0x00007f3246f7c000)
	libXext.so.6 => /usr/lib/libXext.so.6 (0x00007f3246d6a000)
	libX11.so.6 => /usr/lib/libX11.so.6 (0x00007f3246a2b000)
	libXcursor.so.1 => /usr/lib/libXcursor.so.1 (0x00007f3246820000)
	libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x00007f3246498000)
	libm.so.6 => /usr/lib/libm.so.6 (0x00007f3246194000)
	libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007f3245f7d000)
	libc.so.6 => /usr/lib/libc.so.6 (0x00007f3245bdf000)
	libexpat.so.1 => /usr/lib/libexpat.so.1 (0x00007f32459b5000)
	libxcb-dri3.so.0 => /usr/lib/libxcb-dri3.so.0 (0x00007f32457b2000)
	libxcb-present.so.0 => /usr/lib/libxcb-present.so.0 (0x00007f32455af000)
	libxcb-sync.so.1 => /usr/lib/libxcb-sync.so.1 (0x00007f32453a8000)
	libxshmfence.so.1 => /usr/lib/libxshmfence.so.1 (0x00007f32451a5000)
	libglapi.so.0 => /usr/lib/libglapi.so.0 (0x00007f3244f76000)
	libXdamage.so.1 => /usr/lib/libXdamage.so.1 (0x00007f3244d73000)
	libXfixes.so.3 => /usr/lib/libXfixes.so.3 (0x00007f3244b6d000)
	libX11-xcb.so.1 => /usr/lib/libX11-xcb.so.1 (0x00007f324496b000)
	libxcb.so.1 => /usr/lib/libxcb.so.1 (0x00007f3244742000)
	libxcb-glx.so.0 => /usr/lib/libxcb-glx.so.0 (0x00007f3244526000)
	libxcb-dri2.so.0 => /usr/lib/libxcb-dri2.so.0 (0x00007f3244321000)
	libdrm.so.2 => /usr/lib/libdrm.so.2 (0x00007f3244111000)
	libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007f3243ef4000)
	libdl.so.2 => /usr/lib/libdl.so.2 (0x00007f3243cf0000)
	libXrender.so.1 => /usr/lib/libXrender.so.1 (0x00007f3243ae5000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f3247c7a000)
	libXau.so.6 => /usr/lib/libXau.so.6 (0x00007f32438e1000)
	libXdmcp.so.6 => /usr/lib/libXdmcp.so.6 (0x00007f32436db000)

How can i fix this ?

Thanks

**Comment by ds2k5** [comment]
did a complete now download an build
now it works

**Comment by bridgecommand** [comment]
Thanks. I'll close this now. Please let me know if the issue reoccurs.
