### ISSUE TITLE
Is there a way to get a third-person view of the vessel that is being controlled? 

### ISSUE THREAD

**Issue by colford** [bridgecommand/bc#3]
Was wondering if there is a way to get a third-person view of the vessel that is being controlled? I'd like to zoom out of the vessel and see it within the setting of the other objects around it.

**Comment by funscanadian** [comment]
if you use the boat.ini you can create a view using the x y z axis. this will allow you to put the camera offship and allow you to see it in third party.

**Comment by bridgecommand** [comment]
I've added a default elevated view in the ship models in release 5.6.1 (https://github.com/bridgecommand/bc/releases/tag/v5.6.1) so you should now be able to do this without editing any of the ship settings.
