### ISSUE TITLE
.deb package for ubuntu 22.04 

### ISSUE THREAD

**Issue by tobexyz** [bridgecommand/bc#45]
Hi, the [Linux 64 bit (amd64) .deb package](https://bridgecommand.co.uk/file/BridgeCommand5.7.12_amd64.php) is not installable on Ubuntu 22.04 because of missing dependencies (libgcc1 does not exist I think)
However compiling was possible without problems following your instructions.

**Comment by bridgecommand** [comment]
The latest release (5.8.9) now available on https://www.bridgecommand.co.uk/Download has been built and tested on Ubuntu 22.04, please let me know if you have any problems with this.

**Comment by bridgecommand** [comment]
As a follow up note, on Ubuntu, the 'universe' repository must be enabled (for libportaudio2). Please see https://help.ubuntu.com/community/Repositories/Ubuntu for more information on this.

**Comment by tobexyz** [comment]
Thx. for your information and for providing the deb package.
