### ISSUE TITLE
Boat not visibile in radar image when using higher radar resolution

### ISSUE THREAD

**Issue by VariabileAleatoria** [bridgecommand/bc#46]
Hi,
using the bc version compiled from git commit `b7a033eae89101c97ed891cbbf4af1ade1e1ab5d` I'm facing the following issue:
when setting an higher resolution from bc5.ini (RADAR_AngularRes=4096 RADAR_RangeRes=512) boats' shapes on the radar display are not drawn in a visible way.
In the following images there is a comparison between default resolution (RADAR_AngularRes=360 RADAR_RangeRes=128) and the aforementioned.
![360](https://user-images.githubusercontent.com/45683610/203941900-8b28e5b2-43e5-4a46-a856-22eb66eb14c3.png)

![4096](https://user-images.githubusercontent.com/45683610/203941905-b51c1dd7-da63-4dda-9ce6-2bb31f89a73a.png)

**Comment by SNoble6** [comment]
I have the same issue

**Comment by bridgecommand** [comment]
Thanks for pointing this out. It's related to the way the radar scan is implemented in src/RadarCalculation.cpp around line 641, which effectively simplifies a contact to a line. I think this can probably be improved by a relatively small change, which I'll investigate.

**Comment by bridgecommand** [comment]
Commit 86e865c should fix this. The radar contact detection is now doing an additional ellipse check based on the contact's width and length. This should also resolve the problem of buoys becoming invisible on the radar when close.
