### ISSUE TITLE
Problem with building

### ISSUE THREAD

**Issue by ACH1980** [bridgecommand/bc#48]
I have a problem building the code. I tried to find what this error means, but I couldn't.

Here is the output: https://gist.github.com/ACH1980/487b1ae143c41cc3921095a37c1bbbfd

I think relevant is here mainly this section:
```/usr/bin/ld: cannot find -lXcursor
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/bridgecommand-bc.dir/build.make:900: bridgecommand-bc] Error 1
make[1]: *** [CMakeFiles/Makefile2:281: CMakeFiles/bridgecommand-bc.dir/all] Error 2
make: *** [Makefile:91: all] Error 2
[kanjiasdev@desktop1 bin]$
```

**Comment by bridgecommand** [comment]
Hi, it looks like the crucial error message is the line before, "/usr/bin/ld: cannot find -lXcursor". This means that the linker is looking for libxcursor and can't find it.

Hopefully running 'sudo apt-get install cmake mesa-common-dev libxxf86vm-dev freeglut3-dev libxext-dev libxcursor-dev portaudio19-dev libsndfile1-dev' (from https://github.com/bridgecommand/bc/blob/master/src/CompilingLinuxAndMac.txt) will ensure you have the required libraries installed.

Please let me know if this works.

**Comment by ACH1980** [comment]
I'm not on a debian based OS. I'll try to find that lib.

**Comment by ACH1980** [comment]
Found it: `libxcursor-devel` in yum (fedora-based) systems. Now it worked building.
