### ISSUE TITLE
Compilation in VS 2022 doesn't have localization

### ISSUE THREAD

**Issue by psj6** [bridgecommand/bc#52]
Hello, 

I just installed VS 2022 and tried to run it in debug mode. It works but shows this window without fonts and strings of localizations:

![image](https://user-images.githubusercontent.com/96923404/226327646-e53cff7c-690e-4a98-bba8-ebf8388072e1.png)

SDK (in v143)
![image](https://user-images.githubusercontent.com/96923404/226327704-180ef9ff-3eff-48a4-8af9-e6e6522c3c21.png)

What I am doing wrong? How can I debug Bridge Command?

**Comment by bridgecommand** [comment]
Hi. I will need to double check the VS configuration, but in the mean time, please check the working directory configuration in VS (Open Project -> Properties -> Configuration Properties -> Debugging). This should be set to the 'bin' folder location (which contains bc5.ini and other files).

**Comment by psj6** [comment]
Thanks! It worked like a charm. Maybe would be good to do a FAQ with this info. 

Greetings
