### ISSUE TITLE
NMEA server doesn't receive sentences

### ISSUE THREAD

**Issue by psj6** [bridgecommand/bc#53]
Hello, I'm trying to send over UDP on localhost sentences of NMEA, but in the debug point doesn't receive anything.

It stays here giving -1 
![image](https://user-images.githubusercontent.com/96923404/227944392-e1a55eb6-5a59-4d26-a89b-710c8df9893a.png)

I tried everything, from changing ports, firewall, starting server first or sending later, resending other sentences and nothing.

Also I tried the NMEA simulator 1.5.0 and doesn't work too, so I think it's something that the program has that I don't know.

Maybe it's some problem with the asio?

**Comment by psj6** [comment]
Wireshark receives the packet so I'm sending correctly to 127.0.0.1 in the correct port 10111

![image](https://user-images.githubusercontent.com/96923404/227944713-c5a8dd3b-325e-40d2-b50f-4ae3e8422cc3.png)

**Comment by psj6** [comment]
On branch master... maybe it's any issue here?

**Comment by antoine0183** [comment]
A bit of a shot in the dark here since I can't reproduce the problem on my end, but can you see if #55 fixes your issue?

**Comment by psj6** [comment]
Hello @antoine0183 , I tried weeks later and it works. It's perfect and it receives the sentences perfectly.

I was trying with pyenet and maybe created some issue with the ports in my PC and didn't try again.

The code that works for me is:


```
import socket, time

ip = '127.0.0.1'
port = 10111

message = "$RPM,a,odd,50,50.0,A*ff"

sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)

while True:
    sock.sendto(message.encode('utf-8'), (ip, port))
    print("sent message:", message.encode('utf-8'))
    time.sleep(1)

sock.close()
```
