### ISSUE TITLE
Autopilot buffer size

### ISSUE THREAD

**Issue by MaxouPicsou** [bridgecommand/bc#58]
While testing the autopilot functionality I realized that my NMEA frames were not interpreted. While debugging, I noticed that there was a problem with the buffer size and only my first 8 characters were taken into account.

Autopilot was limited to a buffer size of 8 because of the next line:

ssize_t nread = ::read(rcvSocket.native_handle(), buf, sizeof(buf));

sizeof(buf) = 8 because it returns the size of type char * which is a pointer and not a tab size of 128 that was expected.

I push a commit and a pull request.

**Comment by MaxouPicsou** [comment]
fb2f6b2c7194e079f131fee02b4501c5a7f4874a

**Comment by bridgecommand** [comment]
Thanks, I have merged the PR!
