### ISSUE TITLE
Scenario selection window on raspberry pi 5

### ISSUE THREAD

**Issue by flo-ric** [bridgecommand/bc#61]
Compilation on rpi5 (aarch64) works fine but there is an issue with "_bridgecommand-bc_", indeed the scenario selection window doesn't launch.

When the line https://github.com/bridgecommand/bc/blob/d973720da27d025db40945444e193870fe164b23/src/ScenarioChoice.cpp#L107 is commented, the window is launched.

The test `if (device->isWindowActive())` is only present in ScenarioChoice, is this test still relevant  ?

**Comment by bridgecommand** [comment]
Thanks, I don’t think this check is required. It was put in to try and reduce cpu load if the window was in the background, but that’s unlikely to happen much.Is this with Wayland on the raspberry pi?On 11 Oct 2024, at 08:09, flo-ric ***@***.***> wrote:﻿
Compilation on rpi5 (aarch64) works fine but there is an issue with "bridgecommand-bc", indeed the scenario selection window doesn't launch.
When the line https://github.com/bridgecommand/bc/blob/d973720da27d025db40945444e193870fe164b23/src/ScenarioChoice.cpp#L107 is commented, the window is launched.
The test if (device->isWindowActive()) is only present in ScenarioChoice, is this test still relevant  ?

**Comment by flo-ric** [comment]
It would seems indeed, that Wayland is used in the last RPI OS based on Debian 12 Bookworm : https://www.omglinux.com/raspberry-pi-os-bookworm/

I'm going to submit a pull request to remove this condition.
